### ISSUE TITLE
Search capability

### ISSUE THREAD

**Issue by fotiDim** [spotify/ios-app-remote-sdk#6]
Will there be capability to search for Artists, Tracks and Genres? The capability seems to be there on the full Spotify iOS SDK but I don't want to include a separate SDK just for that reason, plus the full iOS SDK seems to be abandonware.

**Comment by arirawr** [comment]
Hey @fotiDim! 

There are no plans to support this for the time being.

I recommend making HTTP calls to the Web API directly, or using a 3rd party open source wrapper library such as [this one](https://github.com/Daltron/Spartan) or [this one](https://github.com/erdtman/spotify-ios-metadata).

**Comment by fotiDim** [comment]
@arirawr I could do that I suppose. If I don't use a 3rd party library how can I get the scope for Web API requests using my access token?

**Comment by arirawr** [comment]
There's a [super lightweight library](https://github.com/spotify/SpotifyLogin) for doing that quickly for now. We're definitely aware of the need for better authentication, though, so stay tuned 👍
